apiVersion: ai.opni.io/v1beta1
kind: OpniCluster
metadata:
  name: opni
  namespace: opni
spec:
  natsCluster:
    name: opni
  opensearch:
    name: opni
    namespace: opni
  s3:
    internal: {}
  services:
    drain:
      workload:
        enabled: false
    gpuController:
      enabled: false
    inference:
      enabled: false
      pretrainedModels:
        - name: opni-model-controlplane
        - name: opni-model-rancher
        - name: opni-model-longhorn
    metrics:
      enabled: false
    opensearchUpdate: {}
    payloadReceiver:
      enabled: false
    preprocessing: {}
    trainingController:
      enabled: false
  version: v0.8.3
---
apiVersion: ai.opni.io/v1beta1
kind: PretrainedModel
metadata:
  name: opni-model-controlplane
  namespace: opni
spec:
  hyperparameters:
    minLogTokens: 1
    modelThreshold: "0.6"
    serviceType: control-plane
  replicas: 1
  source:
    http:
      url: https://opni-public.s3.us-east-2.amazonaws.com/pretrain-models/control-plane-model-v0.4.2.zip
---
apiVersion: ai.opni.io/v1beta1
kind: PretrainedModel
metadata:
  name: opni-model-longhorn
  namespace: opni
spec:
  hyperparameters:
    minLogTokens: 1
    modelThreshold: "0.8"
    serviceType: longhorn
  replicas: 1
  source:
    http:
      url: https://opni-public.s3.us-east-2.amazonaws.com/pretrain-models/longhorn-model-v0.6.0.zip
---
apiVersion: ai.opni.io/v1beta1
kind: PretrainedModel
metadata:
  name: opni-model-rancher
  namespace: opni
spec:
  hyperparameters:
    minLogTokens: 1
    modelThreshold: "0.6"
    serviceType: rancher
  replicas: 1
  source:
    http:
      url: https://opni-public.s3.us-east-2.amazonaws.com/pretrain-models/rancher-model-v0.4.2.zip
