apiVersion: v1
kind: Secret
metadata:
  name: opensearch-credentials
  namespace: opni
data:
  username: {{ .Values.opensearchUsername | b64enc }}
  password: {{ .Values.opensearchPassword | b64enc }}
