apiVersion: v1
kind: Service
metadata:
  name: opni-np
  namespace: opni
spec:
  ports:
    - name: grpc
      port: 9090
      nodePort: 32090
      protocol: TCP
      targetPort: grpc
    - name: noauth
      port: 4000
      nodePort: 32000
      protocol: TCP
      targetPort: noauth
  selector:
    app.kubernetes.io/name: opni-gateway
  type: NodePort
